local M = {}

function M.get(c, opts)
    return {
        CursorColumn     = { fg = c.none, bg = c.nord1 },
        Cursor           = { fg = c.nord0, bg = c.nord4 },
        CursorLine       = { fg = c.none, bg = c.nord1 },
        Error            = { fg = c.nord4, bg = c.nord11 },
        iCursor          = { fg = c.nord0, bg = c.nord4 },
        LineNr           = { fg = c.nord3_bright },
        LineNrAbove      = { fg = c.nord3_bright },
        LineNrBelow      = { fg = c.nord3_bright },
        CursorLineNr     = { fg = c.nord13 },
        MatchParen       = { fg = c.nord13, bg = c.none },
        NonText          = { fg = c.nord2 },
        Normal           = { fg = c.nord4, bg = c.nord0 },
        Pmenu            = { fg = c.nord4, bg = c.nord2 },
        PmenuSbar        = { fg = c.nord4, bg = c.nord2 },
        PmenuSel         = { fg = c.nord8, bg = c.nord3 },
        PmenuThumb       = { fg = c.nord8, bg = c.nord3 },
        SpecialKey       = { fg = c.nord3 },
        SpellBad         = { fg = c.nord11, bg = c.none, undercurl = opts.style.undercurl },
        SpellCap         = { fg = c.nord13, bg = c.none, undercurl = opts.style.undercurl },
        SpellLocal       = { fg = c.nord5, bg = c.none, undercurl = opts.style.undercurl },
        SpellRare        = { fg = c.nord6, bg = c.none, undercurl = opts.style.undercurl },
        Visual           = { fg = c.none, bg = c.nord2 },
        VisualNOS        = { fg = c.none, bg = c.nord2 },
        EndOfBuffer      = { fg = c.nord0 },
        Folded           = { fg = c.nord3_bright, bg = c.nord1, bold = opts.style.bold },
        FoldColumn       = { fg = c.nord3, bg = c.nord0 },
        SignColumn       = { fg = c.nord0 },
        Directory        = { fg = c.nord8, bg = c.none },
        ErrorMsg         = { fg = c.nord4, bg = c.nord11 },
        ModeMsg          = { fg = c.nord4 },
        MoreMsg          = { fg = c.nord8 },
        Question         = { fg = c.nord4 },
        StatusLine       = { fg = c.nord4, bg = c.nord2 },
        StatusLineNC     = { fg = c.nord4, bg = c.nord1 },
        StatusLineTerm   = { fg = c.nord4, bg = c.nord2 },
        StatusLineTermNC = { fg = c.nord4, bg = c.nord1 },
        WarningMsg       = { fg = c.nord0, bg = c.nord13 },
        WildMenu         = { fg = c.nord8, bg = c.nord1 },
        IncSearch        = { fg = c.nord6, bg = c.nord10 },
        Search           = { fg = c.nord1, bg = c.nord8 },
        Substitute       = { fg = c.nord0, bg = c.nord12 },
        Tabline          = { fg = c.nord4, bg = c.nord1 },
        TabLineFill      = { fg = c.nord4, bg = c.nord1 },
        TablineSel       = { fg = c.nord8, bg = c.nord3 },
        Title            = { fg = c.nord4, bg = c.none, bold = opts.style.bold },
        QuickFixLine     = { fg = c.nord4, bg = c.none },

        NormalFloat      = { fg = c.nord4, bg = c.nord2 },
        FloatBorder      = { fg = c.nord4, bg = c.nord2 },

        healthError      = { fg = c.nord11 },
        healthSuccess    = { fg = c.nord14 },
        healthWarning    = { fg = c.nord13 },
        TermCursorNC     = { bg = c.nord1 },

        DiffAdd          = { fg = c.nord14, bg = c.nord0, reverse = true },
        DiffChange       = { fg = c.nord13, bg = c.nord0, reverse = true },
        DiffDelete       = { fg = c.nord11, bg = c.nord0, reverse = true },
        DiffText         = { fg = c.nord9, bg = c.nord0, reverse = true },

        NERDTreeExecFile = { fg = c.nord7 },
        VertSplit        = { fg = c.nord2, bg = c.nord0 },
    }
end

return M
